ALTER TABLE public."TblP126Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126Period" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126Timetable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126BusySlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126Group" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126GroupMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP126GroupInvite" ENABLE ROW LEVEL SECURITY;
